### ISSUE TITLE
WinRM connection err: http response error: 401 - invalid content type

### ISSUE THREAD

**Issue by JLH993** [vmware-samples/packer-examples-for-vsphere#491]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

main

### VMware vSphere

7.0.3j

### HashiCorp Packer

1.8.6

### HashiCorp Packer Plugin for VMware vSphere

1.1.1

### Guest Operating System

windows server 2019 core

### Environment Details

Currently building using the en-us_windows_server_2019_x64_dvd_f9475476.iso file, valid checksum, valid config variables (I was able to build a ubuntu 22.04 template with the build variables). I am running the packer build from a VM in the same vcenter on the same network.

### Description

I am manually starting a build outside of the build.sh script for windows server 2019 since I don't need the desktop environment using the following:

```
packer build -force --only vsphere-iso.windows-server-standard-core -var-file=config/vsphere.pkrvars.hcl -var-file=config/build.pkrvars.hcl -var-file=config/common.pkrvars.hcl builds/windows/server/2019
```
The build goes through fine until I get to the part where it attempts to establish a WinRM connection. Setting the packer debug log to 1 shows the following error over and over again once it gets to this point:

```
2023/02/23 20:22:47 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:47 [INFO] Attempting WinRM connection...
2023/02/23 20:22:47 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:47 [DEBUG] connecting to remote shell using WinRM
2023/02/23 20:22:47 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:47 [ERROR] connection error: http response error: 401 - invalid content type
2023/02/23 20:22:47 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:47 [ERROR] WinRM connection err: http response error: 401 - invalid content type
2023/02/23 20:22:52 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:52 [INFO] Attempting WinRM connection...
2023/02/23 20:22:52 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:52 [DEBUG] connecting to remote shell using WinRM
2023/02/23 20:22:52 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:52 [ERROR] connection error: http response error: 401 - invalid content type
2023/02/23 20:22:52 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:52 [ERROR] WinRM connection err: http response error: 401 - invalid content type
```

Ive let it run for over an hour with no luck. While this was happening, I logged into a console session for the VM its building and I was able to manually re-run the windows-init.ps1 script to see if for some reason it wasnt getting run (this wasn't the case)... I also manually ran the commands to enable winrm, enable basic auth, set AllowUnecrypted to true, set the firewall rules, etc to see if anything was missing but this was not the case either. 

Taking it a step further, I installed the winrm python module on a linux node that lives on the same network to see if I could get more verbose logs from that, and I got the following:

```
>>> import winrm
>>> session = winrm.Session('x.x.x.x', auth=('<redacted-build-username>','<redacted-build-password>'), transport='basic')

>>> result = session.run_ps("hostname")
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/winrm/transport.py", line 271, in _send_message_request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: http://x.x.x.x:5985/wsman

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/winrm/__init__.py", line 50, in run_ps
    rs = self.run_cmd('powershell -encodedcommand {0}'.format(encoded_ps))
  File "/usr/lib/python3/dist-packages/winrm/__init__.py", line 37, in run_cmd
    shell_id = self.protocol.open_shell()
  File "/usr/lib/python3/dist-packages/winrm/protocol.py", line 157, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python3/dist-packages/winrm/protocol.py", line 234, in send_message
    resp = self.transport.send_message(message)
  File "/usr/lib/python3/dist-packages/winrm/transport.py", line 265, in send_message
    response = self._send_message_request(prepared_request, message)
  File "/usr/lib/python3/dist-packages/winrm/transport.py", line 275, in _send_message_request
    raise InvalidCredentialsError("the specified credentials were rejected by the server")
winrm.exceptions.InvalidCredentialsError: the specified credentials were rejected by the server
```

I could however see myself logged in as the build user when accessing the console session, so I know it exists locally. It looks like its rejecting my build credentials, but I am not sure why this would be. I am probably missing something silly, but I wanted to reach out to see if you had run into this before. I have tried to find an answer everywhere before coming here to make sure I wasn't wasting anyone's time. 

### Expected Behavior

When running a packer build for windows server 2019, the winrm session should be established to continue running the automation. 

### Actual Behavior

The build stops at "Establishing a WinRM connection" and does not proceed past this point. 

### Steps to Reproduce

Run the build.sh script for windows server 2019, or run the packer build manually and watch the build logs until they reach the point of establishing a winrm connection. 

### Log Fragments and Files

Packer verbose logs:

```
2023/02/23 20:22:47 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:47 [INFO] Attempting WinRM connection...
2023/02/23 20:22:47 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:47 [DEBUG] connecting to remote shell using WinRM
2023/02/23 20:22:47 packer-plugin-vsphere_v1.1.1_x5.0_linux_amd64 plugin: 2023/02/23 20:22:47 [ERROR] connection error: http response error: 401 - invalid content type
```

Manual WinRM connection attempt logs: 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/winrm/transport.py", line 271, in _send_message_request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: http://x.x.x.x:5985/wsman

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/winrm/__init__.py", line 50, in run_ps
    rs = self.run_cmd('powershell -encodedcommand {0}'.format(encoded_ps))
  File "/usr/lib/python3/dist-packages/winrm/__init__.py", line 37, in run_cmd
    shell_id = self.protocol.open_shell()
  File "/usr/lib/python3/dist-packages/winrm/protocol.py", line 157, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python3/dist-packages/winrm/protocol.py", line 234, in send_message
    resp = self.transport.send_message(message)
  File "/usr/lib/python3/dist-packages/winrm/transport.py", line 265, in send_message
    response = self._send_message_request(prepared_request, message)
  File "/usr/lib/python3/dist-packages/winrm/transport.py", line 275, in _send_message_request
    raise InvalidCredentialsError("the specified credentials were rejected by the server")
winrm.exceptions.InvalidCredentialsError: the specified credentials were rejected by the server
```

### Additional Context

My build.pkrvars.hcl file has each of the following filled out:

```
build_username: "user-name"
build_password: "password" (Includes numbers, upper/lower case, and symbols.)
build_password_encrypted: "present"
build_key: "present"
```

**Comment by tenthirtyam** [comment]
Do you see the same issue on `v23.01`?

**Comment by tenthirtyam** [comment]
Unable to reproduce using `main` from 2023-02-23 using the 

```powershell
packer-examples-for-vsphere on  20230223 

➜ packer init --only vsphere-iso.windows-server-standard-core -var-file=config/vsphere.pkrvars.hcl -var-file=config/build.pkrvars.hcl -var-file=config/common.pkrvars.hcl builds/windows/server/2019

➜ packer build -force --only vsphere-iso.windows-server-standard-core -var-file=config/vsphere.pkrvars.hcl -var-file=config/build.pkrvars.hcl -var-file=config/common.pkrvars.hcl builds/windows/server/2019
vsphere-iso.windows-server-standard-core: output will be in this color.

==> vsphere-iso.windows-server-standard-core: Creating CD disk...
    vsphere-iso.windows-server-standard-core: Creating hybrid image...
    vsphere-iso.windows-server-standard-core: Done copying paths from CD_dirs
==> vsphere-iso.windows-server-standard-core: Uploading packer1059082611.iso to packer_cache/packer1059082611.iso
==> vsphere-iso.windows-server-standard-core: Creating VM...
==> vsphere-iso.windows-server-standard-core: Customizing hardware...
==> vsphere-iso.windows-server-standard-core: Adding SATA controller...
==> vsphere-iso.windows-server-standard-core: Mounting ISO images...
==> vsphere-iso.windows-server-standard-core: Adding configuration parameters...
==> vsphere-iso.windows-server-standard-core: Set boot order...
==> vsphere-iso.windows-server-standard-core: Power on VM...
==> vsphere-iso.windows-server-standard-core: Waiting 2s for boot...
==> vsphere-iso.windows-server-standard-core: Typing boot command...
==> vsphere-iso.windows-server-standard-core: Waiting for IP...
==> vsphere-iso.windows-server-standard-core: IP address: 172.16.14.103
==> vsphere-iso.windows-server-standard-core: Using WinRM communicator to connect: 172.16.14.103
==> vsphere-iso.windows-server-standard-core: Waiting for WinRM to become available...
    vsphere-iso.windows-server-standard-core: WinRM connected.
==> vsphere-iso.windows-server-standard-core: Connected to WinRM!
==> vsphere-iso.windows-server-standard-core: Provisioning with Powershell...
==> vsphere-iso.windows-server-standard-core: Provisioning with powershell script: /Users/johnsonryan/Downloads/packer-examples-for-vsphere/scripts/windows/windows-prepare.ps1
    vsphere-iso.windows-server-standard-core: Setting the Windows Explorer options...
    vsphere-iso.windows-server-standard-core: Disabling system hibernation...
    vsphere-iso.windows-server-standard-core: Disabling TLS 1.0...
    vsphere-iso.windows-server-standard-core: Disabling TLS 1.1...
    vsphere-iso.windows-server-standard-core: Disabling password expiration for the local Administrator accounts...
    vsphere-iso.windows-server-standard-core: Enabling Remote Desktop...
==> vsphere-iso.windows-server-standard-core: Provisioning with Powershell...
==> vsphere-iso.windows-server-standard-core: Provisioning with powershell script: /var/folders/dw/5mlbs0q50gs1qkqmgyx1g6dr0000gp/T/powershell-provisioner1236397219
    vsphere-iso.windows-server-standard-core: Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
    vsphere-iso.windows-server-standard-core: Getting latest version of the Chocolatey package for download.
    vsphere-iso.windows-server-standard-core: Not using proxy.
    vsphere-iso.windows-server-standard-core: Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/1.3.0.
    vsphere-iso.windows-server-standard-core: Downloading https://community.chocolatey.org/api/v2/package/chocolatey/1.3.0 to C:\Users\<sensitive>\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
    vsphere-iso.windows-server-standard-core: Not using proxy.
    vsphere-iso.windows-server-standard-core: Extracting C:\Users\<sensitive>\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\<sensitive>\AppData\Local\Temp\chocolatey\chocoInstall
    vsphere-iso.windows-server-standard-core: Installing Chocolatey on the local machine
    vsphere-iso.windows-server-standard-core: Creating ChocolateyInstall as an environment variable (targeting 'Machine')
    vsphere-iso.windows-server-standard-core:   Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
    vsphere-iso.windows-server-standard-core: WARNING: It's very likely you will need to close and reopen your shell
    vsphere-iso.windows-server-standard-core:   before you can use choco.
    vsphere-iso.windows-server-standard-core: Restricting write permissions to Administrators
    vsphere-iso.windows-server-standard-core: We are setting up the Chocolatey package repository.
    vsphere-iso.windows-server-standard-core: The packages themselves go to 'C:\ProgramData\chocolatey\lib'
    vsphere-iso.windows-server-standard-core:   (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
    vsphere-iso.windows-server-standard-core: A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
    vsphere-iso.windows-server-standard-core:   and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.
    vsphere-iso.windows-server-standard-core:
    vsphere-iso.windows-server-standard-core: Creating Chocolatey folders if they do not already exist.
    vsphere-iso.windows-server-standard-core:
    vsphere-iso.windows-server-standard-core: WARNING: You can safely ignore errors related to missing log files when
    vsphere-iso.windows-server-standard-core:   upgrading from a version of Chocolatey less than 0.9.9.
    vsphere-iso.windows-server-standard-core:   'Batch file could not be found' is also safe to ignore.
    vsphere-iso.windows-server-standard-core:   'The system cannot find the file specified' - also safe.
    vsphere-iso.windows-server-standard-core: chocolatey.nupkg file not installed in lib.
    vsphere-iso.windows-server-standard-core:  Attempting to locate it from bootstrapper.
    vsphere-iso.windows-server-standard-core: PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
    vsphere-iso.windows-server-standard-core: WARNING: Not setting tab completion: Profile file does not exist at
    vsphere-iso.windows-server-standard-core: 'C:\Users\<sensitive>\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
    vsphere-iso.windows-server-standard-core: Chocolatey (choco.exe) is now ready.
    vsphere-iso.windows-server-standard-core: You can call choco from anywhere, command line or powershell by typing choco.
    vsphere-iso.windows-server-standard-core: Run choco /? for a list of functions.
    vsphere-iso.windows-server-standard-core: You may need to shut down and restart powershell and/or consoles
    vsphere-iso.windows-server-standard-core:  first prior to using choco.
    vsphere-iso.windows-server-standard-core: Ensuring Chocolatey commands are on the path
    vsphere-iso.windows-server-standard-core: Ensuring chocolatey.nupkg is in the lib folder
    vsphere-iso.windows-server-standard-core: Chocolatey v1.3.0
    vsphere-iso.windows-server-standard-core: Enabled allowGlobalConfirmation
==> vsphere-iso.windows-server-standard-core: Pausing 30s before the next provisioner...
==> vsphere-iso.windows-server-standard-core: Uploading the Windows update elevated script...
==> vsphere-iso.windows-server-standard-core: Uploading the Windows update check for reboot required elevated script...
==> vsphere-iso.windows-server-standard-core: Uploading the Windows update script...
==> vsphere-iso.windows-server-standard-core: Running Windows update...
    vsphere-iso.windows-server-standard-core: Searching for Windows updates...
    vsphere-iso.windows-server-standard-core: Found Windows update (2021-03-09; 3.12 MB): 2021-01 Update for Windows Server 2019 for x64-based Systems (KB4589208)
    vsphere-iso.windows-server-standard-core: Found Windows update (2022-08-09; 0.07 MB): 2022-08 Security Update for Windows Server 2019 for x64-based Systems (KB5012170)
    vsphere-iso.windows-server-standard-core: Found Windows update (2023-02-14; 76.75 MB): 2023-02 Cumulative Update for .NET Framework 3.5, 4.7.2 and 4.8 for Windows Server 2019 for x64 (KB5022782)
    vsphere-iso.windows-server-standard-core: Skipped (filter) Windows update (2023-02-23; 96.73 MB): Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.383.518.0)
    vsphere-iso.windows-server-standard-core: Found Windows update (2023-02-14; 16846.77 MB): 2023-02 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB5022840)
    vsphere-iso.windows-server-standard-core: Downloading Windows updates (4 updates; 16926.72 MB)...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 32% cpu; 35% memory)...
    vsphere-iso.windows-server-standard-core: Installing Windows updates...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 47% cpu; 45% memory)...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 48% cpu; 55% memory)...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 50% cpu; 58% memory)...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 38% cpu; 63% memory)...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 37% cpu; 65% memory)...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 24% cpu; 64% memory)...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 45% cpu; 61% memory)...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 49% cpu; 51% memory)...
    vsphere-iso.windows-server-standard-core: Waiting for the Windows Modules Installer to exit...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 1% cpu; 48% memory)...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 1% cpu; 48% memory)...
    vsphere-iso.windows-server-standard-core: Waiting for operation to complete (system performance: 1% cpu; 45% memory)...
==> vsphere-iso.windows-server-standard-core: Restarting the machine...
==> vsphere-iso.windows-server-standard-core: Waiting for machine to become available...
==> vsphere-iso.windows-server-standard-core: A system shutdown is in progress.(1115)
==> vsphere-iso.windows-server-standard-core: A system shutdown is in progress.(1115)
==> vsphere-iso.windows-server-standard-core: Checking for pending restart...
    vsphere-iso.windows-server-standard-core: Waiting for the Windows Modules Installer to exit...
==> vsphere-iso.windows-server-standard-core: Restart is still pending...
==> vsphere-iso.windows-server-standard-core: Restarting the machine...
==> vsphere-iso.windows-server-standard-core: Waiting for machine to become available...
==> vsphere-iso.windows-server-standard-core: A system shutdown is in progress.(1115)
==> vsphere-iso.windows-server-standard-core: Checking for pending restart...
    vsphere-iso.windows-server-standard-core: RAINPOL-DCMB222 restarted.
==> vsphere-iso.windows-server-standard-core: Restart complete
==> vsphere-iso.windows-server-standard-core: Running Windows update...
    vsphere-iso.windows-server-standard-core: Searching for Windows updates...
    vsphere-iso.windows-server-standard-core: Skipped (filter) Windows update (2023-02-23; 96.73 MB): Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.383.518.0)
    vsphere-iso.windows-server-standard-core: No Windows updates found
==> vsphere-iso.windows-server-standard-core: Executing shutdown command...
==> vsphere-iso.windows-server-standard-core: Deleting Floppy drives...
==> vsphere-iso.windows-server-standard-core: Eject CD-ROM drives...
==> vsphere-iso.windows-server-standard-core: Deleting CD-ROM drives...
==> vsphere-iso.windows-server-standard-core: Clear boot order...
==> vsphere-iso.windows-server-standard-core: Importing VM OVF template windows-server-2019-standard-core-20230223 to Content Library 'm01-lib01' as the item 'windows-server-2019-standard-core-20230223' with the description 'Version: 20230223
==> vsphere-iso.windows-server-standard-core: Built on: 2023-02-23 21:50 UTC
==> vsphere-iso.windows-server-standard-core: Built by: HashiCorp Packer 1.8.6'...
==> vsphere-iso.windows-server-standard-core: Destroying VM...
==> vsphere-iso.windows-server-standard-core: Running post-processor:  (type manifest)
Build 'vsphere-iso.windows-server-standard-core' finished after 24 minutes 36 seconds.

==> Wait completed after 24 minutes 36 seconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso.windows-server-standard-core: windows-server-2019-standard-core-20230223
--> vsphere-iso.windows-server-standard-core: windows-server-2019-standard-core-20230223
```

**Comment by JLH993** [comment]
Unfortunately yes, I am still seeing the error on the new tag as well. If you are unable to reproduce the issue, its likely something environment related on my end. I tried changing my build user password as well just in case one of the characters were causing an issue for some reason. 

Its also making me think there is something blocking this connection in my environment because I wasn't able to find any other issues describing this same behavior.

**Comment by JLH993** [comment]
Hmm, I actually logged into the console and tried to run windows-prepare.ps1 and it complained about the $BUILD_USERNAME not being set. I assume this could be due to the fact that I ran this outside of packer, so I set the environment variable locally and tried to run again. It got further along in the script but exited while disabling TLS 1.0, so it looks like the script just isnt making it to the point it needs to make it to.

```
    vsphere-iso.windows-server-standard-core: Disabling system hibernation...
2023/02/23 22:50:11 packer-provisioner-powershell plugin: [INFO] RPC client: Communicator ended with: 1
    vsphere-iso.windows-server-standard-core: Disabling TLS 1.0...
    vsphere-iso.windows-server-standard-core: New-Item : A key in this path already exists.
    vsphere-iso.windows-server-standard-core: At C:\Windows\Temp\script-63f7ed88-eabe-58a0-866e-d0523c70ade9.ps1:43 char:1
    vsphere-iso.windows-server-standard-core: + New-Item -Path "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProvid ...
    vsphere-iso.windows-server-standard-core: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vsphere-iso.windows-server-standard-core:     + CategoryInfo          : ResourceExists: (Microsoft.Power...RegistryWrapper:RegistryWrapper) [New-Item], IOExcept
    vsphere-iso.windows-server-standard-core:    ion
    vsphere-iso.windows-server-standard-core:     + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.NewItemCommand
    vsphere-iso.windows-server-standard-core:
2023/02/23 22:50:11 packer-provisioner-powershell plugin: c:/Windows/Temp/script-63f7ed88-eabe-58a0-866e-d0523c70ade9.ps1 returned with exit code 1
2023/02/23 22:50:11 [INFO] (telemetry) ending powershell
```

I manually ran the last part of the script to disable password expiry and enable remote desktop and tried to manually connect over RDP to see if I could access that way. I saw that the account had been locked due to login attempts (likely winrm), so I unlocked the account and the winrm connection was established. 

I will tinker a bit more with this and see if I can get the build to go through by commenting that piece out of the powershell script.

**Comment by JLH993** [comment]
I was able to get a build to complete this morning. I had to edit `windows-prepare.ps1` to comment out the disabling TLS1.0 & TLS1.1 sections, then export the $BUILD_USERNAME environment variable, reset the password of my user, and unlock the account from the winrm login attempts:

```
PS F:\> $env:BUILD_USERNAME = 'user-name'
PS F:\> .\windows-prepare.ps1
Setting the Windows Explorer options...
Disabling system hibernation...
Not disabling TLS1.0... As a test...
Not disabling TLS1.1... As a test...
Disabling password expiration for the local Administrator accounts...
Enabling Remote Desktop...
PS F:\> $Pass = Read-Host -AsSecureString
****************
PS F:\> Get-LocalUser -Name "user-name" | Set-LocalUser -Password -$Pass
PS F:\> net user sre-admin /active:yes
The command completed successfully.

PS F:\>
```
Once doing all of this, I was able to get a build to complete successfully. The issues I ran into were:

-  One or more of the keys being created for disabling TLS 1.0 and TLS 1.2 already existed, which caused the script to exit with an error. 

- Either my build_username/build_password was not being properly set during the prepare script, or the account was being locked quickly due to the winrm login attempts. 

I am not 100% sure on the cause here, but with manual intervention I was able to get a build to go through. Just wanted to follow up with my findings.

**Comment by tenthirtyam** [comment]
Perhaps try it again an only comment out this line:

```powershell
$ErrorActionPreference = 'Stop'
```

**Comment by JLH993** [comment]
@tenthirtyam apologies on the late response here, just getting some time to circle back on this. 

Commenting out the ErrorActionPreference allowed me to get past the point of failing the build on the script, but I was still having issues with the WinRM connection. I tried to manually login using the build_password and was still not able to. My best guess was that one of the characters in my password was causing some sort of issue and not importing properly. 

I tested this by changing the password to something very basic without special characters and WinRM started connecting.  In my case the problem character was an ampersand '&' in my build_password value. I verified this by using the same password previously set without the ampersand and my build went through.

**Comment by tenthirtyam** [comment]
> @tenthirtyam apologies on the late response here, just getting some time to circle back on this.
> 
> Commenting out the ErrorActionPreference allowed me to get past the point of failing the build on the script, but I was still having issues with the WinRM connection. I tried to manually login using the build_password and was still not able to. My best guess was that one of the characters in my password was causing some sort of issue and not importing properly.
> 
> I tested this by changing the password to something very basic without special characters and WinRM started connecting. In my case the problem character was an ampersand '&' in my build_password value. I verified this by using the same password previously set without the ampersand and my build went through.

Makes sense. The password likely needs to be escaped; however, that would likely be an upstream issue with the plugin.
